version: '3'
services:
  notebook:
    container_name: python_notebook
    labels:
      description: Jupyter notebook
      name: jupyter notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    build: .
